version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: aquora-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: contacts_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - aquora-network

volumes:
  postgres-data:

networks:
  aquora-network:
    driver: bridge 